openapi: 3.0.3
info:
  title: OrderServiceApi
  version: 1.0.0
  description: Open Api Order Service-a для заказа товаров из Inventory Service

x-ogen:
  target: shared/pkg/openapi/order/v1
  package: Order
  clean: true
paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml

  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml

  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml

  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
