openapi: 3.0.3
info:
  title: OrderServiceApi
  version: 1.0.0
  description: Open Api Order Service-a для заказа товаров из Inventory Service
paths:
  /api/v1/orders:
    post:
      summary: Создаёт новый заказ на основе выбранных пользователем деталей.
      operationId: CreateOrder
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_order_request'
      responses:
        '200':
          description: Заказ успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order_dto'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_error'
        '402':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden_error'
        '404':
          description: Деталь не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '409':
          description: Конфликт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limit_error'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '502':
          description: Ошибка шлюза
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '503':
          description: Сервис недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
        '555':
          description: Общая ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_error'
  /api/v1/orders/{order_uuid}:
    parameters:
      - $ref: '#/components/parameters/order_uuid'
    get:
      summary: Получение заказа по UUID
      operationId: GetOrderByUuid
      tags:
        - Order
      responses:
        '200':
          description: Заказ успешно найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order_dto'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_error'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden_error'
        '404':
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limit_error'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '502':
          description: Ошибка шлюза
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '503':
          description: Сервис недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
  /api/v1/orders/{order_uuid}/pay:
    parameters:
      - $ref: '#/components/parameters/order_uuid'
    post:
      summary: Оплата заказа
      operationId: PayOrder
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pay_order_request'
      responses:
        '200':
          description: Заказ успешно оплачен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pay_order_response'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_error'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden_error'
        '404':
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '409':
          description: Конфликт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limit_error'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '502':
          description: Ошибка шлюза
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '503':
          description: Сервис недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
  /api/v1/orders/{order_uuid}/cancel:
    parameters:
      - $ref: '#/components/parameters/order_uuid'
    post:
      summary: Отмена заказа
      operationId: CancelOrder
      tags:
        - Order
      responses:
        '204':
          description: Заказ успешно отменён
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error'
        '401':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized_error'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden_error'
        '404':
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/not_found_error'
        '409':
          description: Заказ уже оплачен и не может быть отменён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conflict_error'
        '422':
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validation_error'
        '429':
          description: Превышен лимит запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate_limit_error'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_server_error'
        '502':
          description: Ошибка шлюза
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_gateway_error'
        '503':
          description: Сервис недоступен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service_unavailable_error'
components:
  schemas:
    create_order_request:
      type: object
      required:
        - user_uuid
        - part_uuids
      properties:
        user_uuid:
          type: string
          format: uuid
          description: UUID пользователя
          example: 123e4567-e89b-12d3-a456-426614174000
        part_uuids:
          type: array
          items:
            type: string
            format: uuid
          description: Список UUID деталей для заказа
          example:
            - 123e4567-e89b-12d3-a456-426614174001
            - 123e4567-e89b-12d3-a456-426614174002
          minItems: 1
    payment_method:
      type: string
      enum:
        - UNKNOWN
        - CARD
        - SBP
        - CREDIT_CARD
        - INVESTOR_MONEY
      description: Способ оплаты заказа
      example: CARD
    order_status:
      type: string
      enum:
        - PENDING_PAYMENT
        - PAID
        - CANCELLED
      description: Статус заказа
      example: PENDING_PAYMENT
    order_dto:
      type: object
      required:
        - order_uuid
        - user_uuid
        - part_uuids
        - total_price
        - status
      properties:
        order_uuid:
          type: string
          format: uuid
          description: UUID заказа
          example: 123e4567-e89b-12d3-a456-426614174000
        user_uuid:
          type: string
          format: uuid
          description: UUID пользователя
          example: 123e4567-e89b-12d3-a456-426614174001
        part_uuids:
          type: array
          items:
            type: string
            format: uuid
          description: Список UUID деталей в заказе
          example:
            - 123e4567-e89b-12d3-a456-426614174002
            - 123e4567-e89b-12d3-a456-426614174003
        total_price:
          type: number
          format: double
          description: Итоговая стоимость заказа
          example: 123.45
        transaction_uuid:
          type: string
          format: uuid
          nullable: true
          description: UUID транзакции (если заказ оплачен)
          example: 123e4567-e89b-12d3-a456-426614174004
        payment_method:
          $ref: '#/components/schemas/payment_method'
          nullable: true
          description: Способ оплаты (если заказ оплачен)
        status:
          $ref: '#/components/schemas/order_status'
          description: Статус заказа
    bad_request_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP-код ошибки
          example: 400
        message:
          type: string
          description: плохой запрос
          example: 'Bad Request: Invalid parameter format'
    unauthorized_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: unauthorized error
          example: 401
        message:
          type: string
          description: unauthorized error
          example: unauthorized error
    validation_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: validation error
          example: 402, 422
        message:
          type: string
          description: validation error
          example: validation error
    forbidden_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Forribden Error
          example: 409
        message:
          type: string
          description: не знаю что за ошибка
          example: Forbidden Error ._.
    not_found_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP-код ошибки
          example: 404
        message:
          type: string
          description: не найдено
          example: 'Not Found: 404'
    conflict_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP-код ошибки
          example: 409
        message:
          type: string
          description: Conflict
          example: 'Fatal Error: Conflict'
    rate_limit_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Limit Error
          example: 429
        message:
          type: string
          description: Limit Error
          example: 'Fatal: Limit Error'
    internal_server_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP-код ошибки
          example: 500
        message:
          type: string
          description: внутри сервака ошибка
          example: Fatal Server Error
    bad_gateway_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: bad gateway
          example: 502
        message:
          type: string
          description: Bad gateway
          example: Bad Gateway try again
    service_unavailable_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Service Invalible
          example: 503
        message:
          type: string
          description: Service Invalible
          example: Service Invalible
    generic_error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Generic Error
          example: 555
        message:
          type: string
          description: Ошибка генерации как я понял
          example: Generic Error
    pay_order_request:
      type: object
      required:
        - payment_method
      properties:
        payment_method:
          $ref: '#/components/schemas/payment_method'
          description: Способ оплаты заказа
    pay_order_response:
      type: object
      required:
        - transaction_uuid
      properties:
        transaction_uuid:
          type: string
          format: uuid
          description: UUID транзакции оплаты
          example: 123e4567-e89b-12d3-a456-426614174000
  parameters:
    order_uuid:
      name: order_uuid
      in: path
      required: true
      description: это вкратце айди заказа будет
      schema:
        type: string
        format: uuid
        example: 123e4567-e89b-12d3-a456-426614174000
x-ogen:
  target: shared/pkg/openapi/order/v1
  package: Order
  clean: true
